# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=64)),
                ('urlcontect', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='newsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_type', models.CharField(choices=[(1, '图片'), (2, '文字'), (3, '其他')], default=2, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('createip', models.GenericIPAddressField(null=True, protocol='ipv4')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='newstype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamelives.newsType'),
        ),
    ]
