# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstype',
            name='what_type',
            field=models.CharField(choices=[('pic', '图片'), ('str', '文字'), ('other', '其他')], default=2, max_length=10),
        ),
    ]
