# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelives', '0005_auto_20170908_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstype',
            name='what_type',
            field=models.CharField(choices=[('1', '图片'), ('2', '文字'), ('3', '其他')], default='2', max_length=20),
        ),
    ]
