# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gamelives', '0006_auto_20170908_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='createtime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期'),
        ),
    ]
