# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelives', '0007_auto_20170909_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='sina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=64)),
                ('utlstr', models.CharField(max_length=64)),
            ],
        ),
    ]
