# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelives', '0008_sina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sina',
            name='url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='sina',
            name='utlstr',
            field=models.CharField(max_length=200),
        ),
    ]
