# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelives', '0009_auto_20170910_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='acf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('urlcontent', models.CharField(max_length=300)),
            ],
        ),
    ]
